services:
  backend:
    build:
      context:
        ./back-end-service
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - ./environment.env
    depends_on:
      db-jira-lite:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/actuator/health | grep -q '\"status\":\"UP\"'"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 15s
    networks:
      - app-network
  frontend:
    build:
      context:
        ./front-end-service
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
  db-jira-lite:
    image: postgres:16-alpine
    container_name: db-jira-lite
    env_file:
      - ./environment.env
    volumes:
      - ./back-end-service/src/main/resources/db/init.db.sql:/docker-entrypoint-initdb.d/init.db.sql
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jira_lite"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network
  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoria-metrics
    ports:
      - "8428:8428"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - victoria_metrics_data:/victoria-metrics-data
    command:
      - "-promscrape.config=/etc/prometheus/prometheus.yml"
      - "-retentionPeriod=1M"
    depends_on:
      backend:
        condition:
          service_healthy
    networks:
      - app-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards/json
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - victoria-metrics
    networks:
      - app-network
networks:
  app-network:
    driver:
      bridge
volumes:
  postgres_data:
  victoria_metrics_data:
  grafana_data:
